version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: 'test_assignment'
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql-server
        networks:
            - app-network

    mysql-server:
        image: mysql:8.0.19
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Admin#123
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        links:
            -   mysql-server
        environment:
            PMA_HOST: mysql-server
            PMA_USER: root
            PMA_PASSWORD: Admin#123
            UPLOAD_LIMIT: 300M
        ports:
            - "8080:80"
        networks:
            - app-network
volumes:
    mysql-data:
        driver: "local"

networks:
    app-network:
        driver: "bridge"
